packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  core-js: true
  esbuild: true
  msw: true
  protobufjs: true
  rolldown: true
  sharp: true
minimumReleaseAgeExclude:
  - fumadocs-core@16.11.5
  - fumadocs-ui@16.11.5
  - fumadocs-mdx@15.2.0
